import "@/estilos/contacto.css"
import ContactForm from "@/componentes/contactoform";
export const metadata = {
  title: "Contacto",
  description: " destacadosGenerated by create next app",
};

export default function Contacto() {

  return (
    <main className="holder contacto">
      <div className="columna">
        <h2>Complete el siguiente formulario</h2>
        <ContactForm postUrl="https://camiback-056c1118e855.herokuapp.com/api/contacto" />
      </div>
      <div className="columna datos">
        <h2>Otras vias de contacto</h2>
        <p>Tambien puede contactarse con nosotros usando los siguientes medios:</p>
        <ul>
          <li>Teléfono: 427 5555</li>
          <li>Email: contacto@recetascocteles.com.ar</li>
          <li>Facebook: Recetas de cocteleria</li>
          <li>Twitter: @recetas_cocteleria</li>
          <li>Instagram: @recetas_cocteleria</li>
        </ul>
      </div>
    </main>
  )
}